package gotd

import (
	"net/http"
	"reflect"
	"testing"
	"time"
)

func TestOptionChainsGetOptionChainCall_doRequest(t *testing.T) {
	client := clientTest("", http.StatusOK)
	tdTest, _ := New(client)

	tests := []struct {
		name    string
		c       *OptionChainsGetOptionChainCall
		want    string
		wantErr bool
	}{
		// TODO: Add test cases.
		{"Normal", NewOptionChainsService(tdTest).GetOptionChain("VTI"), "https://api.tdameritrade.com/v1/marketdata/chains?symbol=VTI", false},
		{"SINGLE ", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategySINGLE), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=SINGLE&symbol=VTI", false},
		{"ANALYTICAL ", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyANALYTICAL), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=ANALYTICAL&symbol=VTI", false},
		{"COVERED", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyCOVERED), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=COVERED&symbol=VTI", false},
		{"VERTICAL", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyVERTICAL), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=VERTICAL&symbol=VTI", false},
		{"CALENDAR", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyCALENDAR), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=CALENDAR&symbol=VTI", false},
		{"STRANGLE", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategySTRANGLE), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=STRANGLE&symbol=VTI", false},
		{"STRADDLE", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategySTRADDLE), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=STRADDLE&symbol=VTI", false},
		{"BUTTERFLY", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyBUTTERFLY), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=BUTTERFLY&symbol=VTI", false},
		{"CONDOR", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyCONDOR), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=CONDOR&symbol=VTI", false},
		{"DIAGONAL", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyDIAGONAL), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=DIAGONAL&symbol=VTI", false},
		{"COLLAR", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyCOLLAR), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=COLLAR&symbol=VTI", false},
		{"ROLL", NewOptionChainsService(tdTest).GetOptionChain("VTI").Strategy(OptionChainStrategyROLL), "https://api.tdameritrade.com/v1/marketdata/chains?strategy=ROLL&symbol=VTI", false},
		{"All", NewOptionChainsService(tdTest).
			GetOptionChain("VTI").
			ContractType(OptionChainContractTypeALL).
			StrikeCount(10).
			Strike(10).
			IncludeQuotes(false).
			Strategy(OptionChainStrategyROLL).
			Interval(30).
			Range(OptionChainRangeITM).
			FromDate(time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local)).
			ToDate(time.Date(2020, 1, 1, 0, 0, 0, 0, time.Local)).
			Volatility(40).
			UnderlyingPrice(50).
			InterestRate(60).
			DaysToExpiration(70).
			ExpMonth(OptionChainExpMonthJAN).
			OptionType(OptionChainTypeALL),
			"https://api.tdameritrade.com/v1/marketdata/chains?contractType=ALL&daysToExpiration=70&expMonth=JAN&fromDate=2020-01-01&includeQuotes=FALSE&interestRate=60&interval=30&optionType=ALL&range=ITM&strategy=ROLL&strike=10&strikeCount=10&symbol=VTI&toDate=2020-01-01&underlyingPrice=50&volatility=40", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			rsp, err := tt.c.doRequest()
			if (err != nil) != tt.wantErr {
				t.Errorf("OptionChainsGetOptionChainCall.doRequest() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			got := rsp.Request.URL.String()
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("OptionChainsGetOptionChainCall.doRequest() = %v, want %v", got, tt.want)
			}
		})
	}
}
func TestOptionChainsGetOptionChainCall_Do(t *testing.T) {
	client := clientTest(`{"symbol":"VTI","status":"SUCCESS","underlying":null,"strategy":"SINGLE","interval":null,"isDelayed":true,"isIndex":false,"interestRate":2.48988,"underlyingPrice":139.43,"volatility":29,"daysToExpiration":0,"callExpDateMap":{"2018-11-16:13":{"124.0":[{"putCall":"CALL","symbol":"VTI_111618C124","description":"VTI Nov 16 2018 124 Call","exchangeName":"OPR","bid":14.8,"ask":17,"last":0,"mark":15.9,"bidSize":177,"askSize":167,"lastSize":0,"highPrice":0,"lowPrice":0,"openPrice":0,"closePrice":16.43,"totalVolume":0,"tradeDate":null,"tradeTimeInLong":0,"quoteTimeInLong":1234567890569,"netChange":0,"volatility":40.82,"delta":0.935,"gamma":0.011,"theta":-0.052,"vega":0.034,"rho":0.044,"openInterest":0,"timeValue":0.34,"theoreticalOptionValue":15.901,"theoreticalVolatility":29,"optionDeliverablesList":null,"strikePrice":124,"expirationDate":1234567890000,"daysToExpiration":13,"expirationType":"R","lastTradingDay":1234567890000,"multiplier":100,"settlementType":" ","deliverableNote":"","isIndexOption":null,"percentChange":0,"markChange":-0.53,"markPercentChange":-3.2,"mini":false,"inTheMoney":true,"nonStandard":false}],"125.0":[{"putCall":"CALL","symbol":"VTI_111618C125","description":"VTI Nov 16 2018 125 Call","exchangeName":"OPR","bid":13.8,"ask":16.2,"last":0,"mark":15,"bidSize":198,"askSize":187,"lastSize":0,"highPrice":0,"lowPrice":0,"openPrice":0,"closePrice":15.44,"totalVolume":0,"tradeDate":null,"tradeTimeInLong":0,"quoteTimeInLong":1234567890569,"netChange":0,"volatility":41.312,"delta":0.92,"gamma":0.013,"theta":-0.062,"vega":0.041,"rho":0.043,"openInterest":0,"timeValue":0.44,"theoreticalOptionValue":15.003,"theoreticalVolatility":29,"optionDeliverablesList":null,"strikePrice":125,"expirationDate":1234567890000,"daysToExpiration":13,"expirationType":"R","lastTradingDay":1234567890000,"multiplier":100,"settlementType":" ","deliverableNote":"","isIndexOption":null,"percentChange":0,"markChange":-0.44,"markPercentChange":-2.84,"mini":false,"inTheMoney":true,"nonStandard":false}]},"2018-12-21:48":{"90.0":[{"putCall":"CALL","symbol":"VTI_122118C90","description":"VTI Dec 21 2018 90 Call","exchangeName":"OPR","bid":47.9,"ask":52,"last":0,"mark":49.95,"bidSize":45,"askSize":45,"lastSize":0,"highPrice":0,"lowPrice":0,"openPrice":0,"closePrice":50.41,"totalVolume":0,"tradeDate":null,"tradeTimeInLong":0,"quoteTimeInLong":1234567893701,"netChange":0,"volatility":67.689,"delta":0.97,"gamma":0.002,"theta":-0.023,"vega":0.034,"rho":0.068,"openInterest":5,"timeValue":0.39,"theoreticalOptionValue":49.955,"theoreticalVolatility":29,"optionDeliverablesList":null,"strikePrice":90,"expirationDate":1234567890000,"daysToExpiration":48,"expirationType":"R","lastTradingDay":1234567890000,"multiplier":100,"settlementType":" ","deliverableNote":"","isIndexOption":null,"percentChange":0,"markChange":-0.46,"markPercentChange":-0.92,"mini":false,"inTheMoney":true,"nonStandard":false}],"95.0":[{"putCall":"CALL","symbol":"VTI_122118C95","description":"VTI Dec 21 2018 95 Call","exchangeName":"OPR","bid":43.2,"ask":47,"last":55.2,"mark":45.1,"bidSize":45,"askSize":45,"lastSize":0,"highPrice":0,"lowPrice":0,"openPrice":0,"closePrice":45.43,"totalVolume":0,"tradeDate":null,"tradeTimeInLong":1234567891596,"quoteTimeInLong":1234567898327,"netChange":9.77,"volatility":63.954,"delta":0.959,"gamma":0.003,"theta":-0.028,"vega":0.043,"rho":0.087,"openInterest":0,"timeValue":10.64,"theoreticalOptionValue":45.102,"theoreticalVolatility":29,"optionDeliverablesList":null,"strikePrice":95,"expirationDate":1234567890000,"daysToExpiration":48,"expirationType":"R","lastTradingDay":1234567890000,"multiplier":100,"settlementType":" ","deliverableNote":"","isIndexOption":null,"percentChange":21.5,"markChange":-0.33,"markPercentChange":-0.73,"mini":false,"inTheMoney":true,"nonStandard":false}]}},"putExpDateMap":{"2018-11-16:13":{"124.0":[{"putCall":"PUT","symbol":"VTI_111618P124","description":"VTI Nov 16 2018 124 Put","exchangeName":"OPR","bid":0,"ask":0.2,"last":0,"mark":0.1,"bidSize":0,"askSize":156,"lastSize":0,"highPrice":0,"lowPrice":0,"openPrice":0,"closePrice":0.13,"totalVolume":0,"tradeDate":null,"tradeTimeInLong":0,"quoteTimeInLong":1234567892838,"netChange":0,"volatility":32.472,"delta":-0.029,"gamma":0.007,"theta":-0.022,"vega":0.018,"rho":-0.002,"openInterest":0,"timeValue":0.1,"theoreticalOptionValue":0.101,"theoreticalVolatility":29,"optionDeliverablesList":null,"strikePrice":124,"expirationDate":1234567890000,"daysToExpiration":13,"expirationType":"R","lastTradingDay":1234567890000,"multiplier":100,"settlementType":" ","deliverableNote":"","isIndexOption":null,"percentChange":0,"markChange":-0.03,"markPercentChange":-21.51,"mini":false,"inTheMoney":false,"nonStandard":false}],"125.0":[{"putCall":"PUT","symbol":"VTI_111618P125","description":"VTI Nov 16 2018 125 Put","exchangeName":"OPR","bid":0.05,"ask":0.25,"last":0,"mark":0.15,"bidSize":62,"askSize":209,"lastSize":0,"highPrice":0,"lowPrice":0,"openPrice":0,"closePrice":0.14,"totalVolume":0,"tradeDate":null,"tradeTimeInLong":0,"quoteTimeInLong":1234567892799,"netChange":0,"volatility":33.091,"delta":-0.041,"gamma":0.01,"theta":-0.029,"vega":0.024,"rho":-0.002,"openInterest":0,"timeValue":0.15,"theoreticalOptionValue":0.155,"theoreticalVolatility":29,"optionDeliverablesList":null,"strikePrice":125,"expirationDate":1234567890000,"daysToExpiration":13,"expirationType":"R","lastTradingDay":1234567890000,"multiplier":100,"settlementType":" ","deliverableNote":"","isIndexOption":null,"percentChange":0,"markChange":0.01,"markPercentChange":8.38,"mini":false,"inTheMoney":false,"nonStandard":false}]},"2018-12-21:48":{"90.0":[{"putCall":"PUT","symbol":"VTI_122118P90","description":"VTI Dec 21 2018 90 Put","exchangeName":"OPR","bid":0,"ask":0.5,"last":0.1,"mark":0.25,"bidSize":0,"askSize":444,"lastSize":0,"highPrice":0,"lowPrice":0,"openPrice":0,"closePrice":0,"totalVolume":0,"tradeDate":null,"tradeTimeInLong":1234567898978,"quoteTimeInLong":1234567893215,"netChange":0.1,"volatility":61.894,"delta":-0.02,"gamma":0.002,"theta":-0.016,"vega":0.025,"rho":-0.004,"openInterest":55,"timeValue":0.1,"theoreticalOptionValue":0.252,"theoreticalVolatility":29,"optionDeliverablesList":null,"strikePrice":90,"expirationDate":1234567890000,"daysToExpiration":48,"expirationType":"R","lastTradingDay":1234567890000,"multiplier":100,"settlementType":" ","deliverableNote":"","isIndexOption":null,"percentChange":14185.71,"markChange":0.25,"markPercentChange":35614.29,"mini":false,"inTheMoney":false,"nonStandard":false}],"95.0":[{"putCall":"PUT","symbol":"VTI_122118P95","description":"VTI Dec 21 2018 95 Put","exchangeName":"OPR","bid":0,"ask":0.45,"last":0.15,"mark":0.23,"bidSize":0,"askSize":427,"lastSize":0,"highPrice":0,"lowPrice":0,"openPrice":0,"closePrice":0,"totalVolume":0,"tradeDate":null,"tradeTimeInLong":1234567896721,"quoteTimeInLong":1234567898474,"netChange":0.15,"volatility":54.297,"delta":-0.021,"gamma":0.002,"theta":-0.014,"vega":0.026,"rho":-0.004,"openInterest":12,"timeValue":0.15,"theoreticalOptionValue":0.227,"theoreticalVolatility":29,"optionDeliverablesList":null,"strikePrice":95,"expirationDate":1234567890000,"daysToExpiration":48,"expirationType":"R","lastTradingDay":1234567890000,"multiplier":100,"settlementType":" ","deliverableNote":"","isIndexOption":null,"percentChange":3746.15,"markChange":0.22,"markPercentChange":5669.23,"mini":false,"inTheMoney":false,"nonStandard":false}]}}}`, http.StatusOK)
	tdTest, _ := New(client)

	tests := []struct {
		name    string
		c       *OptionChainsGetOptionChainCall
		want    *OptionChain
		wantErr bool
	}{
		// TODO: Add test cases.
		{"Normal", NewOptionChainsService(tdTest).GetOptionChain("VTI"), &OptionChain{
			ServerResponse:   ServerResponse{200, http.Header{}},
			Symbol:           "VTI",
			Status:           "SUCCESS",
			Underlying:       nil,
			Strategy:         "SINGLE",
			Interval:         0,
			IsDelayed:        true,
			IsIndex:          false,
			InterestRate:     2.48988,
			UnderlyingPrice:  139.43,
			Volatility:       29,
			DaysToExpiration: 0,
			CallExpDateMap: map[string]map[string][]*Option{
				"2018-11-16:13": map[string][]*Option{
					"124.0": []*Option{
						{
							PutCall:                "CALL",
							Symbol:                 "VTI_111618C124",
							Description:            "VTI Nov 16 2018 124 Call",
							ExchangeName:           "OPR",
							Bid:                    14.8,
							Ask:                    17,
							Last:                   0,
							Mark:                   15.9,
							BidSize:                177,
							AskSize:                167,
							LastSize:               0,
							HighPrice:              0,
							LowPrice:               0,
							OpenPrice:              0,
							ClosePrice:             16.43,
							TotalVolume:            0,
							TradeDate:              "",
							TradeTimeInLong:        0,
							QuoteTimeInLong:        1234567890569,
							NetChange:              0,
							Volatility:             40.82,
							Delta:                  0.935,
							Gamma:                  0.011,
							Theta:                  -0.052,
							Vega:                   0.034,
							Rho:                    0.044,
							OpenInterest:           0,
							TimeValue:              0.34,
							TheoreticalOptionValue: 15.901,
							TheoreticalVolatility:  29,
							OptionDeliverablesList: nil,
							StrikePrice:            124,
							ExpirationDate:         1234567890000,
							DaysToExpiration:       13,
							ExpirationType:         "R",
							LastTradingDay:         1234567890000,
							Multiplier:             100,
							SettlementType:         " ",
							DeliverableNote:        "",
							IsIndexOption:          false,
							PercentChange:          0,
							MarkChange:             -0.53,
							MarkPercentChange:      -3.2,
							Mini:                   false,
							InTheMoney:             true,
							NonStandard:            false,
						},
					},
					"125.0": []*Option{
						{
							PutCall:                "CALL",
							Symbol:                 "VTI_111618C125",
							Description:            "VTI Nov 16 2018 125 Call",
							ExchangeName:           "OPR",
							Bid:                    13.8,
							Ask:                    16.2,
							Last:                   0,
							Mark:                   15,
							BidSize:                198,
							AskSize:                187,
							LastSize:               0,
							HighPrice:              0,
							LowPrice:               0,
							OpenPrice:              0,
							ClosePrice:             15.44,
							TotalVolume:            0,
							TradeDate:              "",
							TradeTimeInLong:        0,
							QuoteTimeInLong:        1234567890569,
							NetChange:              0,
							Volatility:             41.312,
							Delta:                  0.92,
							Gamma:                  0.013,
							Theta:                  -0.062,
							Vega:                   0.041,
							Rho:                    0.043,
							OpenInterest:           0,
							TimeValue:              0.44,
							TheoreticalOptionValue: 15.003,
							TheoreticalVolatility:  29,
							OptionDeliverablesList: nil,
							StrikePrice:            125,
							ExpirationDate:         1234567890000,
							DaysToExpiration:       13,
							ExpirationType:         "R",
							LastTradingDay:         1234567890000,
							Multiplier:             100,
							SettlementType:         " ",
							DeliverableNote:        "",
							IsIndexOption:          false,
							PercentChange:          0,
							MarkChange:             -0.44,
							MarkPercentChange:      -2.84,
							Mini:                   false,
							InTheMoney:             true,
							NonStandard:            false,
						},
					},
				},
				"2018-12-21:48": {
					"90.0": []*Option{
						{
							PutCall:                "CALL",
							Symbol:                 "VTI_122118C90",
							Description:            "VTI Dec 21 2018 90 Call",
							ExchangeName:           "OPR",
							Bid:                    47.9,
							Ask:                    52,
							Last:                   0,
							Mark:                   49.95,
							BidSize:                45,
							AskSize:                45,
							LastSize:               0,
							HighPrice:              0,
							LowPrice:               0,
							OpenPrice:              0,
							ClosePrice:             50.41,
							TotalVolume:            0,
							TradeDate:              "",
							TradeTimeInLong:        0,
							QuoteTimeInLong:        1234567893701,
							NetChange:              0,
							Volatility:             67.689,
							Delta:                  0.97,
							Gamma:                  0.002,
							Theta:                  -0.023,
							Vega:                   0.034,
							Rho:                    0.068,
							OpenInterest:           5,
							TimeValue:              0.39,
							TheoreticalOptionValue: 49.955,
							TheoreticalVolatility:  29,
							OptionDeliverablesList: nil,
							StrikePrice:            90,
							ExpirationDate:         1234567890000,
							DaysToExpiration:       48,
							ExpirationType:         "R",
							LastTradingDay:         1234567890000,
							Multiplier:             100,
							SettlementType:         " ",
							DeliverableNote:        "",
							IsIndexOption:          false,
							PercentChange:          0,
							MarkChange:             -0.46,
							MarkPercentChange:      -0.92,
							Mini:                   false,
							InTheMoney:             true,
							NonStandard:            false,
						},
					},
					"95.0": []*Option{
						{
							PutCall:                "CALL",
							Symbol:                 "VTI_122118C95",
							Description:            "VTI Dec 21 2018 95 Call",
							ExchangeName:           "OPR",
							Bid:                    43.2,
							Ask:                    47,
							Last:                   55.2,
							Mark:                   45.1,
							BidSize:                45,
							AskSize:                45,
							LastSize:               0,
							HighPrice:              0,
							LowPrice:               0,
							OpenPrice:              0,
							ClosePrice:             45.43,
							TotalVolume:            0,
							TradeDate:              "",
							TradeTimeInLong:        1234567891596,
							QuoteTimeInLong:        1234567898327,
							NetChange:              9.77,
							Volatility:             63.954,
							Delta:                  0.959,
							Gamma:                  0.003,
							Theta:                  -0.028,
							Vega:                   0.043,
							Rho:                    0.087,
							OpenInterest:           0,
							TimeValue:              10.64,
							TheoreticalOptionValue: 45.102,
							TheoreticalVolatility:  29,
							OptionDeliverablesList: nil,
							StrikePrice:            95,
							ExpirationDate:         1234567890000,
							DaysToExpiration:       48,
							ExpirationType:         "R",
							LastTradingDay:         1234567890000,
							Multiplier:             100,
							SettlementType:         " ",
							DeliverableNote:        "",
							IsIndexOption:          false,
							PercentChange:          21.5,
							MarkChange:             -0.33,
							MarkPercentChange:      -0.73,
							Mini:                   false,
							InTheMoney:             true,
							NonStandard:            false,
						},
					},
				},
			},
			PutExpDateMap: map[string]map[string][]*Option{
				"2018-11-16:13": map[string][]*Option{
					"124.0": []*Option{
						{
							PutCall:                "PUT",
							Symbol:                 "VTI_111618P124",
							Description:            "VTI Nov 16 2018 124 Put",
							ExchangeName:           "OPR",
							Bid:                    0,
							Ask:                    0.2,
							Last:                   0,
							Mark:                   0.1,
							BidSize:                0,
							AskSize:                156,
							LastSize:               0,
							HighPrice:              0,
							LowPrice:               0,
							OpenPrice:              0,
							ClosePrice:             0.13,
							TotalVolume:            0,
							TradeDate:              "",
							TradeTimeInLong:        0,
							QuoteTimeInLong:        1234567892838,
							NetChange:              0,
							Volatility:             32.472,
							Delta:                  -0.029,
							Gamma:                  0.007,
							Theta:                  -0.022,
							Vega:                   0.018,
							Rho:                    -0.002,
							OpenInterest:           0,
							TimeValue:              0.1,
							TheoreticalOptionValue: 0.101,
							TheoreticalVolatility:  29,
							OptionDeliverablesList: nil,
							StrikePrice:            124,
							ExpirationDate:         1234567890000,
							DaysToExpiration:       13,
							ExpirationType:         "R",
							LastTradingDay:         1234567890000,
							Multiplier:             100,
							SettlementType:         " ",
							DeliverableNote:        "",
							IsIndexOption:          false,
							PercentChange:          0,
							MarkChange:             -0.03,
							MarkPercentChange:      -21.51,
							Mini:                   false,
							InTheMoney:             false,
							NonStandard:            false,
						},
					},
					"125.0": []*Option{
						{
							PutCall:                "PUT",
							Symbol:                 "VTI_111618P125",
							Description:            "VTI Nov 16 2018 125 Put",
							ExchangeName:           "OPR",
							Bid:                    0.05,
							Ask:                    0.25,
							Last:                   0,
							Mark:                   0.15,
							BidSize:                62,
							AskSize:                209,
							LastSize:               0,
							HighPrice:              0,
							LowPrice:               0,
							OpenPrice:              0,
							ClosePrice:             0.14,
							TotalVolume:            0,
							TradeDate:              "",
							TradeTimeInLong:        0,
							QuoteTimeInLong:        1234567892799,
							NetChange:              0,
							Volatility:             33.091,
							Delta:                  -0.041,
							Gamma:                  0.01,
							Theta:                  -0.029,
							Vega:                   0.024,
							Rho:                    -0.002,
							OpenInterest:           0,
							TimeValue:              0.15,
							TheoreticalOptionValue: 0.155,
							TheoreticalVolatility:  29,
							OptionDeliverablesList: nil,
							StrikePrice:            125,
							ExpirationDate:         1234567890000,
							DaysToExpiration:       13,
							ExpirationType:         "R",
							LastTradingDay:         1234567890000,
							Multiplier:             100,
							SettlementType:         " ",
							DeliverableNote:        "",
							IsIndexOption:          false,
							PercentChange:          0,
							MarkChange:             0.01,
							MarkPercentChange:      8.38,
							Mini:                   false,
							InTheMoney:             false,
							NonStandard:            false,
						},
					},
				},
				"2018-12-21:48": {
					"90.0": []*Option{
						{
							PutCall:                "PUT",
							Symbol:                 "VTI_122118P90",
							Description:            "VTI Dec 21 2018 90 Put",
							ExchangeName:           "OPR",
							Bid:                    0,
							Ask:                    0.5,
							Last:                   0.1,
							Mark:                   0.25,
							BidSize:                0,
							AskSize:                444,
							LastSize:               0,
							HighPrice:              0,
							LowPrice:               0,
							OpenPrice:              0,
							ClosePrice:             0,
							TotalVolume:            0,
							TradeDate:              "",
							TradeTimeInLong:        1234567898978,
							QuoteTimeInLong:        1234567893215,
							NetChange:              0.1,
							Volatility:             61.894,
							Delta:                  -0.02,
							Gamma:                  0.002,
							Theta:                  -0.016,
							Vega:                   0.025,
							Rho:                    -0.004,
							OpenInterest:           55,
							TimeValue:              0.1,
							TheoreticalOptionValue: 0.252,
							TheoreticalVolatility:  29,
							OptionDeliverablesList: nil,
							StrikePrice:            90,
							ExpirationDate:         1234567890000,
							DaysToExpiration:       48,
							ExpirationType:         "R",
							LastTradingDay:         1234567890000,
							Multiplier:             100,
							SettlementType:         " ",
							DeliverableNote:        "",
							IsIndexOption:          false,
							PercentChange:          14185.71,
							MarkChange:             0.25,
							MarkPercentChange:      35614.29,
							Mini:                   false,
							InTheMoney:             false,
							NonStandard:            false,
						},
					},
					"95.0": []*Option{
						{
							PutCall:                "PUT",
							Symbol:                 "VTI_122118P95",
							Description:            "VTI Dec 21 2018 95 Put",
							ExchangeName:           "OPR",
							Bid:                    0,
							Ask:                    0.45,
							Last:                   0.15,
							Mark:                   0.23,
							BidSize:                0,
							AskSize:                427,
							LastSize:               0,
							HighPrice:              0,
							LowPrice:               0,
							OpenPrice:              0,
							ClosePrice:             0,
							TotalVolume:            0,
							TradeDate:              "",
							TradeTimeInLong:        1234567896721,
							QuoteTimeInLong:        1234567898474,
							NetChange:              0.15,
							Volatility:             54.297,
							Delta:                  -0.021,
							Gamma:                  0.002,
							Theta:                  -0.014,
							Vega:                   0.026,
							Rho:                    -0.004,
							OpenInterest:           12,
							TimeValue:              0.15,
							TheoreticalOptionValue: 0.227,
							TheoreticalVolatility:  29,
							OptionDeliverablesList: nil,
							StrikePrice:            95,
							ExpirationDate:         1234567890000,
							DaysToExpiration:       48,
							ExpirationType:         "R",
							LastTradingDay:         1234567890000,
							Multiplier:             100,
							SettlementType:         " ",
							DeliverableNote:        "",
							IsIndexOption:          false,
							PercentChange:          3746.15,
							MarkChange:             0.22,
							MarkPercentChange:      5669.23,
							Mini:                   false,
							InTheMoney:             false,
							NonStandard:            false,
						},
					},
				},
			},
		}, false},
		// {"Normal", NewOptionChainsService(tdReal).GetOptionChain("VTI"), "VTI", false},
		// {"SINGLE ", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategySINGLE), "VTI", false},
		// {"ANALYTICAL ", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyANALYTICAL), "VTI", false},
		// {"COVERED", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyCOVERED), "VTI", false},
		// {"VERTICAL", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyVERTICAL), "VTI", false},
		// {"CALENDAR", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyCALENDAR), "VTI", false},
		// {"STRANGLE", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategySTRANGLE), "VTI", false},
		// {"STRADDLE", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategySTRADDLE), "VTI", false},
		// {"BUTTERFLY", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyBUTTERFLY), "VTI", false},
		// {"CONDOR", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyCONDOR), "VTI", false},
		// {"DIAGONAL", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyDIAGONAL), "VTI", false},
		// {"COLLAR", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyCOLLAR), "VTI", false},
		// {"ROLL", NewOptionChainsService(tdReal).GetOptionChain("VTI").Strategy(OptionChainStrategyROLL), "VTI", false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := tt.c.Do()
			if (err != nil) != tt.wantErr {
				t.Errorf("OptionChainsGetOptionChainCall.Do() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("OptionChainsGetOptionChainCall.Do() = %v, want %v", got, tt.want)
			}
		})
	}
}
